apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/install.yaml
  - project.yml

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/command/-"
        value: "--disable-auth"
    target:
      kind: Deployment
      name: argocd-server
